// Generated by CoffeeScript 2.3.1
(function() {
  var client, socket;

  socket = new SockJS('/chap_five/stomp_person_message');

  // Effectively wraps SockJS to send STOMP messages over the WebSocket connection.
  client = Stomp.over(socket);

  // Subscribes to '/user/topic/stomp_pers_echo' [@SendToUser("/topic/stomp_pers_echo")]
  client.connect('guest', 'guest', function(frame) {
    console.log('Connected: ' + frame);
    return client.subscribe('/user/topic/stomp_pers_echo', function(greeting) {
      var value;
      value = JSON.parse(greeting.body).message;
      return document.getElementById('msg_reply').value = value;
    });
  });

  this.sendMsg2 = function() {
    var payload;
    console.log('Sending message to \'/app/stomp_pers_shout\'');
    payload = JSON.stringify({
      'message': document.getElementById('msg_input').value
    });
    return client.send('/app/stomp_pers_shout', {}, payload);
  };

}).call(this);

//# sourceMappingURL=stomp_person_message.js.map
