// Generated by CoffeeScript 2.3.1
(function() {
  var sock, url;

  url = `ws://${window.location.host}/chap_five/marco`;

  sock = new WebSocket(url);

  this.sendMsg = function() {
    console.log('Sending message...');
    return sock.send(document.getElementById('msg_input').value);
  };

  sock.onopen = function() {
    return console.log('WebSocket opening...');
  };

  sock.onclose = function() {
    return console.log('WebSocket closing...');
  };

  sock.onmessage = function(e) {
    console.log('Received message: ', e.data);
    return document.getElementById('msg_reply').value = e.data;
  };

}).call(this);

//# sourceMappingURL=websocket_chat.js.map
